### ISSUE TITLE
Please update repo to use the new version of monaco-languageclient V6.0

### ISSUE THREAD

**Issue by AdrianPantea** [TypeFox/monaco-languageclient-ng-example#1]
The current version of [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) is outdated. Please update to V6.0. In particular I would like to see how the monaco tree shaking as defined in your main readme https://github.com/CodinGame/monaco-vscode-api#installation is working becuase I cannot get it to work 

{
  "scripts": {
    "postinstall": "monaco-treemending",
  }
}

**Comment by kaisalmen** [comment]
Hi @AdrianPantea I did not get to update this repo, yet. Thanks you for reminding me.
There is already a PR for the treemending install problems: https://github.com/CodinGame/monaco-vscode-api/pull/115 It links to other issues regarding postinstall problems.

**Comment by AdrianPantea** [comment]
Yeah saw that. Thanks
Using Angular (and Lerna) I cannot get the treemending command to even start executing during my build. Any angular example would help


`postinstall C:\gitRepos\...\ra-ide
     > monaco-treemending

'monaco-treemending' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by kaisalmen** [comment]
Ok, I will update this repo and see if I can re-produce the problem and find a workaround / fix or way-forward.

**Comment by kaisalmen** [comment]
@AdrianPantea I have just pushed an update. It is working again.
I have not added the postinstall step as it seems that the npm packages with `hasInstallScript` seem to run them on `npm install` automatically. It could explains why invoking the postinstall always fails. I have to verify this and if true, update monaco-languagclient README.

**Comment by AdrianPantea** [comment]
OK, I tried following steps:

    >git clone https://github.com/TypeFox/monaco-languageclient-ng-example.git
    >cd monaco-languageclient-ng-example
    >npm i

This gives error:

    ...
    > esbuild@0.17.8 postinstall C:\dev\monaco-languageclient-ng-example\node_modules\@angular-devkit\build-angular\node_modules\esbuild
    > node install.js
    > monaco-languageclient@6.0.1 postinstall C:\dev\monaco-languageclient-ng-example\node_modules\monaco-languageclient
    > monaco-treemending
    'monaco-treemending' is not recognized as an internal or external command,
    operable program or batch file.**


The postInstall in monaco-languageclient is trying to treemend and failing everytime

**Comment by AdrianPantea** [comment]
Are you on a mac or windows OS?

**Comment by AdrianPantea** [comment]
Looks like the tree mending is being pulled in from monaco-languageclient in peer dependency
       https://github.com/TypeFox/monaco-languageclient/blob/main/packages/client/package.json:
with:

```
  "peerDependencies": {
    "vscode": "npm:@codingame/monaco-vscode-api@~1.78.6"
  },
  "scripts": {
...
    "postinstall": "monaco-treemending",
...
  }
```

**Comment by kaisalmen** [comment]
@AdrianPantea this is strange, I just tested it under Linux with a new checkout and it installs and build without errors. It works both on Windows 11 and Ubuntu Linux LTS (22.04). What OS are you on?
You don't use Volta, do you? This ensures the correct node and npm version. Can you provide me with the **node** and **npm** version you use?

It also works with node 16.20.0 and npm 8.19.4 when I downgrade the volta version instructions.

**Comment by kaisalmen** [comment]
@AdrianPantea this is the verbose logging output with node 18.16.0 and npm 9.6.6 on Windows (I opmitted the version info and the failed optional dependency output):
![image](https://github.com/TypeFox/monaco-languageclient-ng-example/assets/21079138/55d4afc6-8793-4318-87b9-dc28f6886644)
and Linux:
![image](https://github.com/TypeFox/monaco-languageclient-ng-example/assets/21079138/f2b2d606-0cbe-4241-9e0a-5d8038e1ce68)
I added a npm script for cleaning the repo `npm run reset:repo`. Everything that does not belong to the checkout is gone afterwards.

**Comment by kaisalmen** [comment]
@AdrianPantea I have updated the README: https://github.com/TypeFox/monaco-languageclient#using-monaco-languageclient

Any project using `monaco-languageclient` is not required to add and run the `postinstall` itself. This done by `monaco-languageclient` during dependency installation (=`npm install`). This is something I have misunderstood.

**Comment by AdrianPantea** [comment]
Upgraded to node V18 from V14 and latest npm V9 and my issue went away. Thanks @kaisalmen
