### ISSUE TITLE
Indicate that `parser.javascript.url: true` is necessary for wasm load

### ISSUE THREAD

**Issue by jhk-mjolner** [TypeFox/monaco-languageclient-ng-example#3]
In the example webpack config there's a few lines that supposed fixes a 'ttf url loading issue':
https://github.com/TypeFox/monaco-languageclient-ng-example/blob/fc631587834c9dfcf9fd1cf8e13b10817d82f6ce/custom-webpack.config.js#L23-L28 

I can attest (https://github.com/CodinGame/monaco-vscode-api/issues/186) that since monaco-languageclient 6.3.0 and monaco-vscode-api 1.80.0 it is also necessary to be able to load the vscode wasm file, and some theme .json files too.

It might not seem like much, but I suggest at least updating the comment to indicate that those lines are now vitally important to be able to load vscode properly, as I had not included the lines in my webpack config, as they seemed to be for a problem I didn't have.

**Comment by kaisalmen** [comment]
@jhk-mjolner thanks for reporting. As said in the other issue help is appreciated.
Otherwise, I am planning to update this with next larger update cycle.

**Comment by jhk-mjolner** [comment]
I'm not sure how much it makes sense to include in the updated comment, but it could include links to https://stackoverflow.com/questions/74038161/angular-cli-and-loading-assets-with-import-meta-url-causing-not-allowed-to-load and https://github.com/angular/angular-cli/issues/24617 for context.

I don't mind it taking a little while to be updated, as just having these two issues exist might be enough to help the next person with the problem.

**Comment by jhk-mjolner** [comment]
Looking at the differences between my webpack config and the one here, I notice that I've previously had to add 
```js
        use: ['style-loader', {
          loader: 'css-loader',
          options: {
            url: false,
          },
        }],
```
to the css rule. 
The change is based on https://github.com/Microsoft/monaco-editor/issues/886#issuecomment-1188678096 and seems to still be necessary for me. I'm not sure if it's anything specific to my case that makes it necessary, or if it should be included in this example.

**Comment by kaisalmen** [comment]
@jhk-mjolner I will see what's needed when I get to it. 😆 What you found is already very helpful and will help me fix things when updating the deps/config here. I will include any helpful links directly the config.
